### PR TITLE
Running on TF 1.7

### PR DESCRIPTION
**Pull request by klintan**
Some fixes that have been discussed as issues. 

One question about:

`flags.DEFINE_integer("emb_mat", 0, "embedding matrix")`

But perhaps somebody could comment on that, (as well as other things as well of course)

### CODE REVIEW

**Comment by JosephAntony1** [comment]
worked for me thanks 👍

**Comment by fooSynaptic** [comment]
Sorry, i still got exception while complete the fix onto the source code.

`Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/sde/jiaxin_hu/git_project/bi-att-flow/basic/cli.py", line 127, in <module>
    tf.app.run()
  File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/data/sde/jiaxin_hu/git_project/bi-att-flow/basic/cli.py", line 124, in main
    m(config)
  File "/data/sde/jiaxin_hu/git_project/bi-att-flow/basic/main.py", line 23, in main
    _train(config)
  File "/data/sde/jiaxin_hu/git_project/bi-att-flow/basic/main.py", line 82, in _train
    models = get_multi_gpu_models(config)
  File "/data/sde/jiaxin_hu/git_project/bi-att-flow/basic/model.py", line 19, in get_multi_gpu_models
    model = Model(config, scope, rep=gpu_idx == 0)
  File "/data/sde/jiaxin_hu/git_project/bi-att-flow/basic/model.py", line 58, in __init__
    self._build_forward()
  File "/data/sde/jiaxin_hu/git_project/bi-att-flow/basic/model.py", line 95, in _build_forward
    xx = multi_conv1d(Acx, filter_sizes, heights, "VALID",  self.is_train, config.keep_prob, scope="xx")
  File "/data/sde/jiaxin_hu/git_project/bi-att-flow/my/tensorflow/nn.py", line 253, in multi_conv1d
    concat_out = tf.concat(2, outs)
  File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1178, in concat
    dtype=dtypes.int32).get_shape().assert_is_compatible_with(
  File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 950, in convert_to_tensor
    as_ref=False)
  File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1040, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 433, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 344, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.`

**Comment by Ign0reLee** [comment]
> Sorry, i still got exception while complete the fix onto the source code.
> 
> `Traceback (most recent call last): File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main "__main__", mod_spec) File "/usr/lib/python3.5/runpy.py", line 85, in _run_code exec(code, run_globals) File "/data/sde/jiaxin_hu/git_project/bi-att-flow/basic/cli.py", line 127, in <module> tf.app.run() File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run _sys.exit(main(argv)) File "/data/sde/jiaxin_hu/git_project/bi-att-flow/basic/cli.py", line 124, in main m(config) File "/data/sde/jiaxin_hu/git_project/bi-att-flow/basic/main.py", line 23, in main _train(config) File "/data/sde/jiaxin_hu/git_project/bi-att-flow/basic/main.py", line 82, in _train models = get_multi_gpu_models(config) File "/data/sde/jiaxin_hu/git_project/bi-att-flow/basic/model.py", line 19, in get_multi_gpu_models model = Model(config, scope, rep=gpu_idx == 0) File "/data/sde/jiaxin_hu/git_project/bi-att-flow/basic/model.py", line 58, in __init__ self._build_forward() File "/data/sde/jiaxin_hu/git_project/bi-att-flow/basic/model.py", line 95, in _build_forward xx = multi_conv1d(Acx, filter_sizes, heights, "VALID", self.is_train, config.keep_prob, scope="xx") File "/data/sde/jiaxin_hu/git_project/bi-att-flow/my/tensorflow/nn.py", line 253, in multi_conv1d concat_out = tf.concat(2, outs) File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1178, in concat dtype=dtypes.int32).get_shape().assert_is_compatible_with( File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 950, in convert_to_tensor as_ref=False) File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1040, in internal_convert_to_tensor ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref) File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function return constant(v, dtype=dtype, name=name) File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant value, dtype=dtype, shape=shape, verify_shape=verify_shape)) File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 433, in make_tensor_proto _AssertCompatible(values, dtype) File "/data/sde/jiaxin_hu/git_project/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 344, in _AssertCompatible (dtype.name, repr(mismatch), type(mismatch).__name__)) TypeError: Expected int32, got list containing Tensors of type '_Message' instead.`


Hello, I do not know if this will help, but I have the same problem.

For me, I changed the concat_out = tf.concat (2, outs) command on line 248 in ./my/tensorflow/nn.py to concat_out = tf.concat (outs, 2).

The concat command was found to be a problem with the version being changed and the order of the args changed. I hope it helps.

**Comment by klintan** [comment]
Closing this one, since TF is now much newer and there are much better alternatives out there.

**Pull request closed without merging**
